temp_files = metadata.filepath((metadata.expt_id == expi(e) &...
                        metadata.stage_id == stgs(s) & ...
                        metadata.arm == arms(1) & ...
                        ismember(metadata.hours, [0,20,40,80,116])) | ...
                        (metadata.expt_id == expi(e) &...
                        metadata.stage_id == stgs(s) & ...
                        metadata.arm == arms(2) & ...
                        ismember(metadata.hours, [0,6,12,18,22])));
                    
destFolder = '/Users/SBP29/Desktop/Methionine/Overexpression/03_PS1_';

for f = 1:length(temp_files)
    movefile(temp_files(f), destFolder);
end